services:
  django:
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
        # published: 8000 # uncomment for local dev
    environment:
      - DEBUG=False # set to "True" for local dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          memory: 512M
