# Generated by Django 5.2.3 on 2025-06-27 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('border_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificate_templates/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/')),
                ('title_font_size', models.PositiveIntegerField(default=24)),
                ('body_font_size', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField()),
                ('final_score', models.PositiveIntegerField(help_text='Final course score percentage')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
